# Generated by Django 4.0.5 on 2022-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0003_delete_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_man', models.CharField(max_length=120)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='dz.books')),
            ],
        ),
    ]
